### ISSUE TITLE
Helper Dirs sub folder

### ISSUE THREAD

**Issue by JonDum** [altano/handlebars-loader#7]
I cannot figure this out for the life of me.

I have a folder structure like this:

    ▸ css/
    ▸ js/
    ▸ pages/
    ▾ templates/
         ▾ helpers/
              ▾ admin/
                  aHelper.js
              ▾ foo/
                  fooHelper.js
                  fooHelper2.js
              ▾ bar/
                  fooHelper2.js
                genericHelper.js
                anotherHelper.js
            template1.handlebars
            template2.handlebars
            template3.handlebars

I want to be able to use helpers like this:

    <div {{foo/fooHelper}}>
        {{bar/barHelper.js}}
    </div>
    <span {{{anotherHelper.js}}></span>

It works fine if I keep the the helpers directory flat. But that doesn't scale very well with a lot of helpers.

I've tried {{$foo/fooHelper}}, {{/templates/helpers/adflkj}}, {{$helpers/bar/adfadf}} and just about every combination thereof.

Any ideas?

Here's my `webpack.config.js`:

    module.exports = {
        entry: "./js/main.js",
        output: {
            path: __dirname + "/build/js",
            filename: "main.js?[hash]",
            chunkFilename: "[hash]/js/[id].js",
        },
        resolve: {
            modulesDirectories: ["node_modules", "bower_components", "css", "js", 'templates', 'templates/helpers', 'templates/helpers/foo'],
            fallback: [__dirname+'/templates/helpers', __diraname+'/templates/helpers/foo']
        },
        module: {
            loaders: [
                {test:/\.styl$/, loader:'style-loader!css-loader!stylus-loader'},
                {test: /\.css$/, loader: "style-loader!css-loader"},
                {test: /\.png$/, loader: "url-loader?limit=100000&mimetype=image/png"},
                {test: /\.jpg$/, loader: "file-loader"},
                {test: /\.(handlebars|hbt|hbs)/, loader: "handlebars-loader"}
            ],
            resolve: {
                extensions: ['', '.js', '.styl']
            }
        },
        plugins: [
            new webpack.ResolverPlugin(new webpack.ResolverPlugin.DirectoryDescriptionFilePlugin("bower.json", ["main"]))
        ]
    }

**Comment by altano** [comment]
You can absolutely accomplish this.  The issue you hit is an intentional limitation in Handlebars, not this loader.  You cannot use forward slashes in Handlebars identifiers, which includes helper names, without escaping them with brackets.  You can see in [this JSFiddle](http://jsfiddle.net/altano/pputqj42/2/) that it is required with just Handlebars.

So the solution is to just put your helper name, when it has nested folders, in angle brackets.

I created [this example](https://github.com/altano/handlebars-loader/tree/master/examples/helperDirs) to illustrate how to do it.

Please let me know if you have any more issues.
